name: nice 

options:
  bundleIdPrefix: io.github.takeiteasy
  createIntermediateGroups: true
  deploymentTarget:
    macOS: "15.0"

settings:
  CLANG_CXX_LANGUAGE_STANDARD: c++17
  CLANG_CXX_LIBRARY: libc++
  GCC_C_LANGUAGE_STANDARD: c11
  CLANG_WARN_DOCUMENTATION_COMMENTS: false

targets:
  nice:
    type: tool
    platform: macOS
    sources:
        - path: src/
          includes:
            - "*.h"
            - "*.[ch]pp"
        - path: deps/fmt
          includes:
            - "*.cc"
          excludes:
            - "fmt.cc"
        - path: deps/imgui/backends/imgui_impl_metal.mm
        - path: deps/ini.c
        - path: deps/INIReader.cpp
        - path: deps/
          type: folder
        - path: assets/
          type: folder
        - path: build/
          type: folder
        - path: test/
          type: folder
        - path: project.yml
          type: folder
        - path: Makefile
          type: folder
        - path: README.md 
          type: folder
    dependencies:
        - sdk: Cocoa.framework
        - sdk: IOKit.framework
        - sdk: Metal.framework
        - sdk: MetalKit.framework
        - sdk: Quartz.framework
        - sdk: AudioToolbox.framework
        - target: flecs
    settings:
        HEADER_SEARCH_PATHS: [$(PROJECT_DIR)/deps,
                              $(PROJECT_DIR)/build,
                              $(PROJECT_DIR)/deps/flecs,
                              $(PROJECT_DIR)/deps/imgui]
        OTHER_CFLAGS: [-x objective-c++, -DSOKOL_METAL]
  flecs:
    type: library.static
    platform: macOS
    sources:
        - path: deps/flecs
          excludes:
            - "imgui_demo.cpp"
        - path: deps/minilua.c
    settings:
        HEADER_SEARCH_PATHS: [$(PROJECT_DIR)/deps,
                              $(PROJECT_DIR)/deps/flecs]
